[package]
name = "regops"
version = "0.1.2"
edition = "2024"
authors     = ["Romain SUZANNE <romzorus591@gmail.com>"]
repository  = "https://github.com/regent-project/regops.git"
license     = "Apache-2.0"
description = "GitOps agent for localhost configuration management"
keywords    = ["automation", "configuration", "management", "infrastructure", "observability"]
categories  = ["config"]

[dependencies]
gix = { version = "0.87.1", features = ["blocking-network-client", "blocking-http-transport-reqwest", "blocking-http-transport-reqwest-rust-tls"] }
hostname = "0.4.2"
regent-sdk = "0.9.5"
serde = { version = "1.0.229", features = ["derive"] }
tokio = { version = "1.53.1", features = ["full"] }
toml = "1.1.4"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["fmt", "registry", "json", "env-filter"] }
yaml_serde = "0.10.7"

[profile.release]
lto = true


[package.metadata.deb]
maintainer = "Romain SUZANNE <romzorus591@gmail.com>"
maintainer-scripts = "debian/"
copyright = "2026, Romain SUZANNE <romzorus591@gmail.com>"
license-file = ["LICENSE"]
conf-files = ["/etc/regops/config.toml"]
extended-description = """\
 GitOps agent for localhost configuration management"""
depends = "$auto"
section = "utility"
priority = "optional"
assets = [
    ["target/release/regops", "usr/bin/regops", "755"],
    ["systemd/regops.service", "lib/systemd/system/regops.service", "644"],
    ["default_config/config.toml", "etc/regops/config.toml", "644"]
]
