[Git]
# repo = "https://my.git.server/my/git/repository.git"
branch = "main"
local_path = "/tmp/regops"
expected_state_path = "expected_state.yaml"

[SystemIntegration]
log_level = "Info"
log_format = "Raw"

[Behavior]
mode = "Enforce"
interval_sec = 30