#!/bin/sh
set -e

case "$1" in
    configure)
        if ! getent passwd regops > /dev/null; then
            useradd --system \
                    --user-group \
                    --home-dir /home/regops \
                    --create-home \
                    --shell /usr/sbin/nologin \
                    regops
        fi
        # Cover the case where the user pre-existed without a proper home.
        install -d -o regops -g regops /home/regops

        echo "regops ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/regops
        chmod 0440 /etc/sudoers.d/regops
        visudo -cf /etc/sudoers.d/regops

        systemctl daemon-reload
        systemctl enable regops.service
        systemctl try-restart regops.service
        
        # Generate and install shell completion scripts
        if [ -x /usr/bin/regops ]; then
            # Bash completion
            install -d -m 755 /usr/share/bash-completion/completions
            /usr/bin/regops completion bash > /usr/share/bash-completion/completions/regops
            chmod 644 /usr/share/bash-completion/completions/regops
            
            # Zsh completion
            install -d -m 755 /usr/share/zsh/site-functions
            /usr/bin/regops completion zsh > /usr/share/zsh/site-functions/_regops
            chmod 644 /usr/share/zsh/site-functions/_regops
            
            # Fish completion
            install -d -m 755 /usr/share/fish/vendor_completions.d
            /usr/bin/regops completion fish > /usr/share/fish/vendor_completions.d/regops.fish
            chmod 644 /usr/share/fish/vendor_completions.d/regops.fish
        fi
        ;;
esac