#!/bin/sh
set -e

case "$1" in
    configure)
        if ! getent passwd regops > /dev/null; then
            useradd --system \
                    --user-group \
                    --home-dir /home/regops \
                    --create-home \
                    --shell /usr/sbin/nologin \
                    regops
        fi
        # Cover the case where the user pre-existed without a proper home.
        install -d -o regops -g regops /home/regops

        echo "regops ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/regops
        chmod 0440 /etc/sudoers.d/regops
        visudo -cf /etc/sudoers.d/regops

        systemctl daemon-reload
        systemctl enable regops.service
        systemctl try-restart regops.service
        ;;
esac