[Git]
repo = "https://github.com/regent-project/RegOps.git"
branch = "main"
local_path = "/tmp/regops"
expected_state_path = "examples/state.yaml"

[SystemIntegration]
log_level = "Info"
log_format = "Raw"

[Behavior]
mode = "Enforce"
interval_sec = 10